estate_pro/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name ='signup'),
    path('change_password/', auth_views.PasswordChangeView.as_view(
        template_name='accounts/password_change.html'), name = 'password_change'),
    path('change_password/success/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_success.html'),
        name = 'password_change_done'),
    path('<int:pk>/details/', views.UserDetailsView.as_view(), name='details_view'),
    path('<int:pk>/details/edit/', views.DetailsUpdate.as_view(), name='details_update'),
    path('chat/', views.InboxChatView.as_view(), name='chat'),
    path('chat/<int:pk>/reply/', views.ChatReplyView.as_view(), name='chat_details'),
]

estate_pro/estate_app/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'estate_app'

urlpatterns = [
    path('create/', views.PropertyCreateView.as_view(), name="property_create"),
    path('', views.PropertyListView.as_view(), name='property_list_view'),
    path('myoffers/', views.MyOfferList.as_view(), name='my_offers_list'),
    path('myoffers/<int:pk>/delete/', views.PropertyDeleteView.as_view(), name='delete_property'),
    path('myoffers/<int:pk>/edit/', views.PropertyEditView.as_view(), name='edit_property' ),
    path('<str:username>/offers/', views.UserOffersList.as_view(), name='user_offers_view'),
    path('offers/<int:pk>/', views.PropertyDetailView.as_view(), name='property_detail_view'),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

estate_pro/estate_pro/urls.py
from django.contrib import admin
# from django.conf.urls.static import static
from django.urls import path, include

# from . import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', include('estate_app.urls', namespace='offers')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
]

estate_pro/estate_app/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib import auth
from django.core.validators import MaxValueValidator
from model_utils import Choices

from django.contrib.auth import get_user_model
User = get_user_model()



class PropertyModel(models.Model):
    author      = models.ForeignKey(User, on_delete=models.CASCADE,
            related_name = 'estates')
    title       = models.CharField(max_length = 128)
    text        = models.TextField(max_length = 10000)
    price       = models.PositiveIntegerField(
            validators=[MaxValueValidator(1000000000)]) #MAX VALUE
    city        = models.CharField(max_length = 64)
    # district = models.CharField(max_length = 32)
    # street = models.CharField(max_length = 64)
    # post_code = models.CharField(max_length = 6)
    types       = Choices('Flat', 'House', 'Plot')
    estate_type = models.CharField(choices=types, default=types.Flat, max_length=8)
    # estate_type = models.IntegerField(choices = estate_types, default = 'Flat')
    # surface_area = models.PositiveIntegerField(max_value = 999)

    def __str__(self):
      return self.title


class ImagesModel(models.Model):
    property = models.ForeignKey(PropertyModel, related_name = 'images', on_delete=models.CASCADE)
    image = models.ImageField( verbose_name = 'Image') #upload_to = get_filename,

class UserMessages(models.Model):
    title        = models.CharField(max_length = 255)
    message      = models.TextField(max_length = 5000)
    msg_sender   = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'msg_sender')
    msg_receiver = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'msg_receiver')
    is_read      = models.BooleanField(default = False)

    def __str__(self):
        return self.title

    def read_msg(self):
        self.is_read = True
        self.save()

estate_pro/estate_app/forms.py
from django import forms

from . import models


class PropertyForm(forms.ModelForm):

    class Meta():
        model = models.PropertyModel
        exclude = ['author',]

#
class ImagesForm(forms.ModelForm):

    # images = forms.FileField(widget=forms.FileInput(attrs={'multiple': True}))
    class Meta():
        model = models.ImagesModel
        fields = ('image', )

ImagesCreateFormSet = forms.inlineformset_factory(models.PropertyModel, models.ImagesModel,
 form = ImagesForm, max_num=3, validate_max=True, extra = 3, can_delete = True)

class MessagesForm(forms.ModelForm):

    class Meta():
        model = models.UserMessages
        fields = ['title', 'message']

estate_pro/estate_app/views.py
from django.shortcuts import redirect, render, render_to_response
from django.http import HttpResponseRedirect
from django.views.generic import  DetailView, ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django_filters.views import BaseFilterView


from . import models
from . import forms
from . import filters

User = get_user_model()

class AuthorRequiredMixin:
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.author != self.request.user:
            return redirect('estate_app:my_offers_list')
        return super(AuthorRequiredMixin, self).dispatch(request, *args, **kwargs)

class PropertyDetailView(CreateView):

    form_class = forms.MessagesForm
    template_name = 'estate_app/propertymodel_detail.html'

    def get_success_url(self):
        propertyid = self.kwargs['pk']
        return reverse_lazy('estate_app:property_detail_view', kwargs={'pk': propertyid})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['propertymodel'] = models.PropertyModel.objects.get(id = self.kwargs['pk'])
        context['form'] = self.get_form(forms.MessagesForm)
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.msg_sender = self.request.user
        self.object.msg_receiver = models.PropertyModel.objects.get(id = self.kwargs['pk']).author
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

class PropertyListView(BaseFilterView, ListView):

    model = models.PropertyModel
    paginate_by = 1
    filterset_class = filters.PropertyFilter

class PropertyCreateView(LoginRequiredMixin, CreateView):

    fields = ('title', 'text', 'price', 'city', 'estate_type')
    model = models.PropertyModel
    template_name = 'estate_app/property_create_form.html'

    def form_valid(self, form, formset):
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, formset):
        print( formset)
        if form.is_valid() == False:
            print("FORM INVALID")
        if formset.is_valid() == False:
            print("FORMSET INVALID")
        return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get_success_url(self):
        return reverse_lazy('estate_app:my_offers_list')

    def get(self, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset = forms.ImagesCreateFormSet(queryset=models.ImagesModel.objects.none())
        template_name = 'estate_app/property_create_form.html'
        return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset = forms.ImagesCreateFormSet(self.request.POST, self.request.FILES or None)
        if (form.is_valid() and formset.is_valid()):
            self.object = form.save(commit=False)
            self.object.author = self.request.user
            self.object.save()
            for img in formset:
                try:
                    photo = models.ImagesModel(property = self.object, image = img.cleaned_data['image'])
                    photo.save()
                except Exception as e:
                    pass
            return self.form_valid(form, formset)
        else:
            return self.form_invalid(form, formset)

class PropertyEditView(AuthorRequiredMixin, LoginRequiredMixin,  UpdateView):
    fields = ('title', 'text', 'price', 'city', 'estate_type')
    model = models.PropertyModel
    template_name = 'estate_app/propertymodel_edit.html'

    def get(self, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset = forms.ImagesCreateFormSet(instance = self.object)
        return self.render_to_response(self.get_context_data(form = form, formset = formset))

    def post(self, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset = forms.ImagesCreateFormSet(self.request.POST, self.request.FILES, instance=self.object)

        if (form.is_valid() and formset.is_valid()):
            self.object = form.save()
            for img in formset:

                try:
                    if not img.instance.pk:
                        photo = models.ImagesModel(property = self.object, image = img.cleaned_data['image'])
                        photo.save()

                    elif img.cleaned_data['DELETE']:
                        photo = models.ImagesModel.objects.get(pk = img.instance.id)
                        photo.delete()

                    else:
                        photo = models.ImagesModel.objects.get(pk = img.instance.id)
                        photo.image = img.cleaned_data['image']
                        photo.save()

                except Exception as e:
                    pass

            return self.form_valid(form, formset)
        else:
            return self.form_invalid(form, formset)

    def form_invalid(self, form, formset):
        return self.render_to_response(self.get_context_data(form = form, formset = formset))

    def form_valid(self, form, formset):
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        propertyid = self.kwargs['pk']
        return reverse_lazy('estate_app:property_detail_view', kwargs={'pk': propertyid})

class PropertyDeleteView(AuthorRequiredMixin, LoginRequiredMixin, DeleteView):
    model = models.PropertyModel
    template_name = 'estate_app/delete_property.html'

    def get_success_url(self):
        return reverse_lazy('estate_app:my_offers_list')

class MyOfferList(LoginRequiredMixin, BaseFilterView, ListView):

    model = models.PropertyModel
    template_name = 'estate_app/my_offers_list.html'
    paginate_by = 1
    filterset_class = filters.PropertyFilter

    def get_queryset(self):
        return models.PropertyModel.objects.filter(author=self.request.user).order_by('-id')

class UserOffersList(BaseFilterView, ListView):

    model = models.PropertyModel
    template_name = 'estate_app/user_offers_list.html'
    paginate_by = 1
    filterset_class = filters.PropertyFilter

    def get_queryset(self):
        return models.PropertyModel.objects.filter(author = User.objects.get(username = self.kwargs['username'])).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_author'] = self.kwargs['username']
        return context

estate_pro/estate_app/templates/estate_app/delete_property.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

  <h1> Do you wanna delete {{propertymodel.title}}? </h1>

  <form method="post">
    {% csrf_token %}
    <input type="submit" name="" value="Delete">

  </form>

{% endblock %}

estate_pro/estate_app/templates/estate_app/my_offers_list.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load my_tags %}


{% block content %}

<div class="col-sm-10 blogShort">
  <form method="GET">
    <h3>Filter my offers:</h3>
    <br>
    {{filter.form.as_table}}
    <br>
    <br>
    <input class="btn btn-default" type="submit" value="Filter!">
    <a class="btn btn-default" href="{%url 'estate_app:property_list_view' %}">Reset Filters!</a>
  </form>
  <br>
</div>

   {% for offer in object_list %}

    <div class="col-sm-10 pull-right blogShort">
        <h1>{{offer.title}}</h1>
        <div class="col-sm-4 pull-left">
          <img src="{% get_first_photo offer.id %}" alt="post img" class="pull-left img-responsive margin10 img-thumbnail profile-img">
        </div>

        <article><p>
            Description: {% cut_text offer.text %} <br>
            Price: {{offer.price}} <br>
            City: {{offer.city}}
          </p></article>

        <a class="btn btn-blog pull-right marginBottom10" href="{% url 'estate_app:property_detail_view' offer.id %}">READ MORE</a>
    </div>
  {% endfor %}
  <div class="paginator col-sm-10">
    {% if is_paginated %}
      {% if page_obj.has_previous %}
        <a href="?{% url_replace request 'page' page_obj.previous_page_number %}"> Previous </a>
      {% endif %}
      {{page_obj}}
      {% if page_obj.has_next %}
        <a href="?{% url_replace request 'page' page_obj.next_page_number %}"> Next </a>
      {% endif %}
    {% endif %}
  </div>



{% endblock %}

estate_pro/estate_app/templates/estate_app/property_create_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="col-sm-10 pull-right blogShort">
  <h1>Create your offer:</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    {{formset.as_p}}
    <input class="btn btn-default" type="submit" value="Create!">

  </form>
</div>
{% endblock %}

estate_pro/estate_app/templates/estate_app/propertymodel_detail.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

<div class="col-sm-8 blogShort">

  <h1>{{propertymodel.title}} </h1>
  <p>Author: <a href="{% url 'estate_app:user_offers_view' propertymodel.author %}">{{propertymodel.author}}</a> </p>
  <p>Price: {{propertymodel.price}} </p>
  <p>City: {{propertymodel.city}} </p>
  <p>Estate type: {{propertymodel.estate_type}} </p>
  <p>Property description: {{propertymodel.text}} </p>

  <div class="row gallery">
    {% for image in propertymodel.images.all %}
      <a href="{{image.image.url}}"><img src="{{image.image.url}}" alt="Image Not Found" class="img-thumbnail col-sm-4"></a>
    {% endfor %}
  </div>
  <br>
  {% if propertymodel.author == user %}
    <p> <a class="btn btn-default" href="{% url 'estate_app:delete_property' pk=propertymodel.id %}">DELETE</a>
     <a class="btn btn-default" href="{% url 'estate_app:edit_property' pk=propertymodel.id %}">EDIT</a></p>
  {% endif %}
</div>
<div class="col-sm-2 pull-right">
  <br>
  <p>Author: <a href="{% url 'estate_app:user_offers_view' propertymodel.author %}">{{propertymodel.author}}</a> </p>
  <p>Name: {{propertymodel.author.name}}</p>
  <p>Phone: {{propertymodel.author.phone_num}}</p>
</div>
{% if user.is_authenticated %}
  <div class="col-sm-10 blogShort pull-right">
    <h1>Send message to the author:</h1>
    <form method="post">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" name="" value="Send Message">

    </form>
  </div>
{% endif %}

{% endblock %}

estate_pro/estate_app/templates/estate_app/propertymodel_edit.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

<div class="col-sm-10">
  <h1>Edit your offer:</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}

    {{formset.management_form}}
    {% for f in formset %}
    <p>  {{f.id}}{{f.image}} </p>
      {% if f.instance.id %}
      <p>  Delete: {{f.DELETE}} </p>
      {% endif %}
    {% endfor %}

    <input class="btn btn-default" type="submit" value="Edit!">

  </form>
</div>
{% endblock %}

estate_pro/estate_app/templates/estate_app/propertymodel_list.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load my_tags %}

{% block content %}

  <div class="col-sm-10 blogShort">
    <form method="GET">
      <h3>Filter:</h3>
      <br>
      {{filter.form.as_table}}
      <br>
      <br>
      <input class="btn btn-default" type="submit" value="Filter!">
      <a class="btn btn-default" href="{%url 'estate_app:property_list_view' %}">Reset Filters!</a>
    </form>
    <br>
  </div>

     {% for offer in object_list %}

      <div class="col-sm-10 pull-right blogShort">
          <h1>{{offer.title}}</h1>
          <div class="col-sm-4 pull-left">
            <img src="{% get_first_photo offer.id %}" alt="post img" class="pull-left img-responsive margin10 img-thumbnail profile-img">
          </div>

          <article><p>
              Description: {% cut_text offer.text %} <br>
              Price: {{offer.price}} <br>
              City: {{offer.city}}
            </p></article>

          <a class="btn btn-blog pull-right marginBottom10" href="{% url 'estate_app:property_detail_view' offer.id %}">READ MORE</a>
      </div>
    {% endfor %}
    <div class="paginator col-sm-10">
      {% if is_paginated %}
        {% if page_obj.has_previous %}
          <a href="?{% url_replace request 'page' page_obj.previous_page_number %}"> Previous </a>
        {% endif %}
        {{page_obj}}
        {% if page_obj.has_next %}
          <a href="?{% url_replace request 'page' page_obj.next_page_number %}"> Next </a>
        {% endif %}
      {% endif %}
    </div>



{% endblock %}

estate_pro/estate_app/templates/estate_app/user_offers_list.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load my_tags %}

{% block content %}

<h1></h1>
<div class="col-sm-10 blogShort">
  <form method="GET">
    <h3>Filter {{current_author}}'s offers:</h3>
    <br>
    {{filter.form.as_table}}
    <br>
    <br>
    <input class="btn btn-default" type="submit" value="Filter!">
    <a class="btn btn-default" href="{%url 'estate_app:property_list_view' %}">Reset Filters!</a>
  </form>
  <br>
</div>

   {% for offer in object_list %}

    <div class="col-sm-10 pull-right blogShort">
        <h1>{{offer.title}}</h1>
        <div class="col-sm-4 pull-left">
          <img src="{% get_first_photo offer.id %}" alt="post img" class="pull-left img-responsive margin10 img-thumbnail profile-img">
        </div>

        <article><p>
            Description: {% cut_text offer.text %} <br>
            Price: {{offer.price}} <br>
            City: {{offer.city}}
          </p></article>

        <a class="btn btn-blog pull-right marginBottom10" href="{% url 'estate_app:property_detail_view' offer.id %}">READ MORE</a>
    </div>
  {% endfor %}
  <div class="paginator col-sm-10">
    {% if is_paginated %}
      {% if page_obj.has_previous %}
        <a href="?{% url_replace request 'page' page_obj.previous_page_number %}"> Previous </a>
      {% endif %}
      {{page_obj}}
      {% if page_obj.has_next %}
        <a href="?{% url_replace request 'page' page_obj.next_page_number %}"> Next </a>
      {% endif %}
    {% endif %}
  </div>

{% endblock %}