estate_pro/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name ='signup'),
    path('change_password/', auth_views.PasswordChangeView.as_view(
        template_name='accounts/password_change.html'), name = 'password_change'),
    path('change_password/success/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_success.html'),
        name = 'password_change_done'),
    path('<int:pk>/details/', views.UserDetailsView.as_view(), name='details_view'),
    path('<int:pk>/details/edit/', views.DetailsUpdate.as_view(), name='details_update'),
    path('chat/', views.InboxChatView.as_view(), name='chat'),
    path('chat/<int:pk>/reply/', views.ChatReplyView.as_view(), name='chat_details'),
]

estate_pro/estate_pro/urls.py
from django.contrib import admin
# from django.conf.urls.static import static
from django.urls import path, include

# from . import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', include('estate_app.urls', namespace='offers')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
]

estate_pro/accounts/models.py
from django.db import models
from django.contrib import auth
from django.contrib.auth.models import User

class UserDetails(models.Model):
    user         = models.OneToOneField(User, on_delete=models.CASCADE,
                    related_name = 'details', primary_key=True)

    phone_num    = models.PositiveIntegerField(blank=True, null=True) #blank=True
    name         = models.CharField(max_length = 255, blank=True, null=True) #blank=True

    def __str__(self):
        return self.user.username

estate_pro/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

from . import models


class UserSignUpForm(UserCreationForm):

    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

class DetailsForm(forms.ModelForm):

    class Meta:
        fields = ('name', 'phone_num')
        model = models.UserDetails

UserDetailsFormSet = forms.inlineformset_factory(models.User, models.UserDetails,
    form = DetailsForm, max_num=1, validate_max=True, extra = 1, can_delete = False)

estate_pro/accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db.models import OuterRef, Subquery, Q

from . import forms
from . import models
from estate_app import models as estate_models
from estate_app import forms as estate_forms

class AuthorRequiredMixin:
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != self.request.user:
            return redirect('estate_app:my_offers_list')
        return super().dispatch(request, *args, **kwargs)

class SignUp(CreateView):

    form_class = forms.UserSignUpForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form, formset):
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('accounts:login')

    def form_invalid(self, form, formset):
        return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def get(self, *args, **kwargs):
        self.object = None
        form_class = forms.UserSignUpForm
        form = self.get_form(form_class)
        formset = forms.UserDetailsFormSet(queryset=models.UserDetails.objects.none())
        template_name = 'accounts/signup.html'
        return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset = forms.UserDetailsFormSet(self.request.POST or None)

        if (form.is_valid() and formset.is_valid()):
            self.object = form.save()
            for f in formset:
                details = f.save(commit=False)
                details.user = self.object
                details.save()

            return self.form_valid(form, formset)
        else:
            return self.form_invalid(form, formset)

class UserDetailsView(DetailView):

    model = models.UserDetails
    template_name = 'accounts/user_details.html'

class DetailsUpdate(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    fields = ('phone_num', 'name')
    model = models.UserDetails
    template_name = 'accounts/details_edit.html'

    def get_success_url(self):
     return reverse_lazy('accounts:details_view', kwargs = {'pk' : self.request.user.id})

class ChatReplyView(LoginRequiredMixin, CreateView):

    model = estate_models.UserMessages
    template_name = 'accounts/chat_reply.html'
    fields = ('title', 'message')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        messages = estate_models.UserMessages.objects.filter(
            msg_receiver = self.request.user, msg_sender = self.kwargs['pk'])

        for msg in messages:
            if msg.is_read == False:
                estate_models.UserMessages.objects.get(
                id = msg.id).read_msg()

        context['form'] = self.get_form(estate_forms.MessagesForm)
        context['usermessages_list'] = estate_models.UserMessages.objects.filter((
            (Q(msg_receiver = self.request.user) & Q(msg_sender = self.kwargs['pk']))
            | (Q(msg_receiver = self.kwargs['pk']) & Q(msg_sender = self.request.user)))).order_by('-pk')
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.msg_sender = self.request.user
        self.object.msg_receiver = User.objects.get(id = self.kwargs['pk'])
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        chat_with = self.kwargs['pk']
        return reverse_lazy('accounts:chat_details', kwargs={'pk': chat_with})

class InboxChatView(LoginRequiredMixin, ListView):

    model = estate_models.UserMessages
    template_name = 'accounts/Chat_list.html'

    def get_queryset(self):
        subq = estate_models.UserMessages.objects.filter(
            msg_receiver = self.request.user.id, msg_sender = OuterRef('msg_sender')).order_by('-id')
        final = estate_models.UserMessages.objects.filter(pk=Subquery(subq.values('pk')[:1]))
        return final.order_by('-id')

estate_pro/accounts/templates/accounts/Chat_list.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load my_tags %}

{% block content %}

<div class="col-sm-10 pull-right blogShort">

  <h1>Chats with:</h1>
  {% for msg in usermessages_list %}

    <p><h1><a href="{% url 'accounts:chat_details' pk=msg.msg_sender.id %}">
    {% cut_text msg.title %} by {{msg.msg_sender}} ({% unread_from_user msg.msg_sender.id msg.msg_receiver.id %}) </a></h1>

  {% endfor %}
</div>

{% endblock %}

estate_pro/accounts/templates/accounts/chat_reply.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
<h1>Reply:</h1>
<div class="col-sm-10 pull-right blogShort">
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input class="btn btn-default" type="submit" name="" value="Send Message">
  </form>
</div>


{% for msg in usermessages_list %}
  {% if msg.msg_sender == user %}
  <div class="col-sm-10 pull-right blogShort">
    <div class="col-sm-9 pull-right">
      <div>
        <h3 class="pull-right">Title: {{msg.title}}</h3>
      </div>
      <div class="msg-by-user">
        <br> <br> <br>
          {{msg.message}} 
          <br> by you
      </div>
    </div>
  </div>
  {% else %}
  <div class="col-sm-10 pull-right blogShort">
    <div class="col-sm-9 pull-left">
      <div>
        <h3 class="pull-left">Title: {{msg.title}}</h3>
      </div>
      <div class="msg-by-other">
        <br> <br> <br>
        {{msg.message}} <br>
        by {{msg.msg_sender}}
      </div>
    </div>
  </div>
  {% endif %}

{% endfor %}



{% endblock %}

estate_pro/accounts/templates/accounts/details_edit.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="col-sm-10">
    <h1> Edit Details</h1>
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-default" value="Edit!">

    </form>
  </div>
</div>
{% endblock %}

estate_pro/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

  <div class="col-sm-10 container">
    <h1> Log In</h1>
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-default" value="Login!">
      <a class="btn btn-default" href="{% url 'accounts:signup' %}"> Sign up! </a>

    </form>
  </div>

{% endblock %}

estate_pro/accounts/templates/accounts/password_change.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <h1> Log In</h1>
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-default" value="Change Password!">

    </form>
  </div>
</div>
{% endblock %}

estate_pro/accounts/templates/accounts/password_change_success.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="jumbotron">
  <h1>PASSWORD CHANGED SUCCESSFULLY!</h1>
  </div>
</div>
{% endblock %}

estate_pro/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="col-sm-10 container margin100">
  <h1> Sing Up</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_formset formset %}
    <input type="submit" class="btn btn-default" value="Sign Up!">
  </form>

</div>
<br><br>
{% endblock %}

estate_pro/accounts/templates/accounts/user_details.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

  <div class="col-sm-10 pull-right blogShort">
    <h1> {{userdetails.user}} details</h1>
    <p>Name:
    {% if userdetails.name != None %}
      {{userdetails.name}}
    {% endif %}
    </p>
    <p>Phone number:
    {% if userdetails.phone_num != None %}
      {{userdetails.phone_num}}
    {% endif %}
    </p>

    {% if userdetails.user.id == user.id %}
      <p>
      <a href="{% url 'accounts:details_update' pk=user.id %}">Edit!</a>
      </p>
    {% endif %}

  </div>

{% endblock %}