estate_pro/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name ='signup'),
    path('change_password/', auth_views.PasswordChangeView.as_view(
        template_name='accounts/password_change.html'), name = 'password_change'),
    path('change_password/success/', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_success.html'),
        name = 'password_change_done'),
    path('<int:pk>/details/', views.UserDetailsView.as_view(), name='details_view'),
    path('<int:pk>/details/edit/', views.DetailsUpdate.as_view(), name='details_update'),
    path('chat/', views.InboxChatView.as_view(), name='chat'),
    path('chat/<int:pk>/reply/', views.ChatReplyView.as_view(), name='chat_details'),
]

estate_pro/estate_app/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'estate_app'

urlpatterns = [
    path('create/', views.PropertyCreateView.as_view(), name="property_create"),
    path('', views.PropertyListView.as_view(), name='property_list_view'),
    path('myoffers/', views.MyOfferList.as_view(), name='my_offers_list'),
    path('myoffers/<int:pk>/delete/', views.PropertyDeleteView.as_view(), name='delete_property'),
    path('myoffers/<int:pk>/edit/', views.PropertyEditView.as_view(), name='edit_property' ),
    path('<str:username>/offers/', views.UserOffersList.as_view(), name='user_offers_view'),
    path('offers/<int:pk>/', views.PropertyDetailView.as_view(), name='property_detail_view'),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

estate_pro/estate_pro/urls.py
from django.contrib import admin
# from django.conf.urls.static import static
from django.urls import path, include

# from . import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('', include('estate_app.urls', namespace='offers')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
]

estate_pro/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load my_tags %}
<html lang="en" dir="ltr">
  <head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="{% static 'estate_pro/css/master.css' %}" type="text/css">

    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <img class="bg-picture" src="{% static 'estate_pro/city.PNG' %}" alt="">
    <div class="container">
	     <div id="blog" class="row">

          <div class="col-sm-2 paddingTop20">
            <nav class="nav-sidebar">
                <ul class="nav">
                    <li class="active"><a href="{%url 'estate_app:property_list_view' %}"><span class="glyphicon glyphicon-star"></span> Estates</a></li>
                    {% if user.is_authenticated %}
                      <li><a href="{% url 'estate_app:property_create' %}">Create offer</a></li>
                      <li><a href="{% url 'estate_app:my_offers_list' %}">My Offers</a></li>
                      <li><a href="{% url 'accounts:chat' %}">
                        Inbox: {% total_messages user.id %} <b> ({% unread_messages user.id %})</b> </a> </li>
                      <li> <a href="{% url 'accounts:details_view' pk=user.id %}">Profile</a></li>
                      <li class="nav-divider"></li>
                      <li><a href="{% url 'accounts:logout'%}"><i class="glyphicon glyphicon-off"></i> Log out</a></li>
                    {% else %}
                      <li class="nav-divider"></li>
                      <li> <a href="{% url 'accounts:login' %}"><i class="glyphicon glyphicon-off"></i> Log in </a></li>
                    {% endif %}
                </ul>
            </nav>
                      <div><h2 class="add">Place for your add!</h2></div>
        </div>

        {% block content %}
        {% endblock %}

      <div class="col-md-12 gap10"></div>
     </div>
    </div>
  </body>
</html>

estate_pro/templates/index.html
<!DOCTYPE html>
{% load static %}
{% load msg_tags %}
<html lang="en" dir="ltr">
  <head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="{% static 'estate_pro/css/master.css' %}" type="text/css">

    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  <div class="container">
	 <div id="blog" class="row">

                  <div class="col-sm-2 paddingTop20">
            <nav class="nav-sidebar">
                <ul class="nav">
                    <li class="active"><a href="{%url 'estate_app:property_list_view' %}"><span class="glyphicon glyphicon-star"></span> Estates</a></li>
                    {% if user.is_authenticated %}
                      <li><a href="{% url 'estate_app:property_create_form' %}">Create offer</a></li>
                      <li><a href="{% url 'estate_app:my_offers_list' %}">My Offers</a></li>
                      <li><a href="{% url 'accounts:chat' %}">
                        Inbox: {% total_messages user.id %} <b> ({% unread_messages user.id %})</b> </a> </li>
                      <li> <a href="{% url 'accounts:details_view' pk=user.id %}">Profile</a></li>
                      <li class="nav-divider"></li>
                      <li><a href="{% url 'accounts:logout'%}"><i class="glyphicon glyphicon-off"></i> Log out</a></li>
                    {% else %}
                      <li class="nav-divider"></li>
                      <li> <a href="{% url 'accounts:login' %}"><i class="glyphicon glyphicon-off"></i> Log in </a></li>
                    {% endif %}
                </ul>
            </nav>
                      <div><h2 class="add">Place for your add!</h2></div>
        </div>

        {% block content %}
        {% endblock %}
                 <!-- <div class="col-md-10 blogShort">
                     <h1>Title 1</h1>
                     <img src="http://www.kaczmarek-photo.com/wp-content/uploads/2012/06/guinnes-150x150.jpg" alt="post img" class="pull-left img-responsive thumb margin10 img-thumbnail">


                     <article><p>
                         Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text
                         ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only
                         five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release
                         of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of
                         Lorem Ipsum.
                         </p></article>
                     <a class="btn btn-blog pull-right marginBottom10" href="http://bootsnipp.com/user/snippets/2RoQ">READ MORE</a>
                 </div> -->

               <div class="col-md-12 gap10"></div>
             </div>
</div>
  </body>
</html>

estate_pro/templates/test.html
{%extends "base.html"%}

{% block content %}
    <h1>You are logged in!</h1>

{% endblock %}

estate_pro/templates/thanks.html
{%extends "base.html"%}

{% block content %}
    <h1>You are logged off!</h1>

{% endblock %}